/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "fpu_init.h"
#include "hcsr04.h"
#include "FreeRTOS.h"
#include "task.h"
#include "semphr.h"
#include "iwdg.h"
#include "event_groups.h"
#include "stm32f4xx.h"

volatile uint32_t pulse_width;

#define SENSOR_TASK_BIT (1 << 0)

SemaphoreHandle_t EchoSemaphore;
EventGroupHandle_t IWDG_eventgroup;

int main(void){
	FPU_Init();
	HCSR04_Init();
	IWDG_Init();

	EchoSemaphore = xSemaphoreCreateBinary();
	IWDG_eventgroup = xEventGroupCreate();

	if(EchoSemaphore != NULL && IWDG_eventgroup != NULL){
		SensorTask_Init();
		WatchDogTask_Init();
	    }

	    vTaskStartScheduler();

	  while(1){}
}

void EXTI1_IRQHandler(void){

	if(EXTI_PR & (1 << 1)){

		EXTI_PR |= (1 << 1);
		if(GPIOA_IDR & (1 << 1)){
			TIM2_CNT = 0;
		}
		else{
			pulse_width = TIM2_CNT;

			BaseType_t xHigherPriorityTaskWoken = pdFALSE;
			xSemaphoreGiveFromISR( EchoSemaphore, &xHigherPriorityTaskWoken);
			portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
		}
	}

}

void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName){

	(void)xTask;
	(void)pcTaskName;


	GPIOA_MODER &= ~(3U << 10);
	GPIOA_MODER |= (1U << 10);

	TIM2_CR1 |= (1 << 0);

	GPIOA_ODR &= ~(1 << 0);
	while(1){
		GPIOA_ODR ^= (1 << 5);

		while(TIM2_CNT <= 1000000){
			__asm("NOP"); // No Operation
		}

		TIM2_CNT = 0;
	}

}
